# Wazuh Helm chart values for local deployment on Fedora Atomic

# Global settings
global:
  environment: local
  nodeAffinity: {}
  podAffinity: {}
  podAntiAffinity: {}

# Wazuh indexer (Elasticsearch) configuration
indexer:
  enabled: true
  replicas: 1  # Single node for local deployment
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistence:
    enabled: true
    storageClassName: local-path
    size: 30Gi
  javaOpts: "-Xms1g -Xmx1g"
  config:
    opensearch.yml: |
      cluster.name: wazuh-cluster
      node.name: ${HOSTNAME}
      network.host: 0.0.0.0
      discovery.seed_hosts: ["wazuh-indexer"]
      cluster.initial_master_nodes: ["wazuh-indexer-0"]
      bootstrap.memory_lock: true
      plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/config/certs/indexer.pem
      plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/config/certs/indexer-key.pem
      plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
      plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/config/certs/indexer.pem
      plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/config/certs/indexer-key.pem
      plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/config/certs/root-ca.pem
      plugins.security.allow_default_init_securityindex: true
      plugins.security.authcz.admin_dn:
        - "CN=admin,O=Wazuh,OU=Wazuh"
      plugins.security.nodes_dn:
        - "CN=indexer,O=Wazuh,OU=Wazuh"
      plugins.security.ssl.transport.enforce_hostname_verification: false
      action.auto_create_index: ".security,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*"

# Wazuh dashboard (Kibana) configuration
dashboard:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  service:
    type: ClusterIP
  config:
    opensearch_dashboards.yml: |
      server.host: 0.0.0.0
      server.port: 5601
      opensearch.hosts: https://wazuh-indexer:9200
      opensearch.ssl.verificationMode: certificate
      opensearch.username: kibanaserver
      opensearch.password: kibanaserver
      opensearch.requestHeadersWhitelist: ["securitytenant", "Authorization"]
      opensearch_security.multitenancy.enabled: false
      opensearch_security.readonly_mode.roles: ["kibana_read_only"]
      server.ssl.enabled: true
      server.ssl.key: /usr/share/wazuh-dashboard/config/certs/dashboard-key.pem
      server.ssl.certificate: /usr/share/wazuh-dashboard/config/certs/dashboard.pem
      opensearch.ssl.certificateAuthorities: ["/usr/share/wazuh-dashboard/config/certs/root-ca.pem"]
      uiSettings.overrides.defaultRoute: /app/wazuh

# Wazuh manager configuration
manager:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  persistence:
    enabled: true
    storageClassName: local-path
    size: 10Gi
  service:
    type: ClusterIP
  config:
    ossec.conf: |
      <ossec_config>
        <global>
          <jsonout_output>yes</jsonout_output>
          <alerts_log>yes</alerts_log>
          <logall>no</logall>
          <logall_json>no</logall_json>
          <email_notification>no</email_notification>
          <smtp_server>smtp.example.wazuh.com</smtp_server>
          <email_from>wazuh@example.wazuh.com</email_from>
          <email_to>recipient@example.wazuh.com</email_to>
          <email_maxperhour>12</email_maxperhour>
          <email_log_source>alerts.log</email_log_source>
        </global>

        <alerts>
          <log_alert_level>3</log_alert_level>
          <email_alert_level>12</email_alert_level>
        </alerts>

        <remote>
          <connection>secure</connection>
          <port>1514</port>
          <protocol>tcp</protocol>
          <queue_size>131072</queue_size>
        </remote>

        <rootcheck>
          <disabled>no</disabled>
          <check_files>yes</check_files>
          <check_trojans>yes</check_trojans>
          <check_dev>yes</check_dev>
          <check_sys>yes</check_sys>
          <check_pids>yes</check_pids>
          <check_ports>yes</check_ports>
          <check_if>yes</check_if>
          <frequency>43200</frequency>
          <rootkit_files>/var/ossec/etc/rootcheck/rootkit_files.txt</rootkit_files>
          <rootkit_trojans>/var/ossec/etc/rootcheck/rootkit_trojans.txt</rootkit_trojans>
          <skip_nfs>yes</skip_nfs>
        </rootcheck>

        <wodle name="cis-cat">
          <disabled>yes</disabled>
          <timeout>1800</timeout>
          <interval>1d</interval>
          <scan-on-start>yes</scan-on-start>
          <java_path>wodles/java</java_path>
          <ciscat_path>wodles/ciscat</ciscat_path>
        </wodle>

        <wodle name="osquery">
          <disabled>yes</disabled>
          <run_daemon>yes</run_daemon>
          <log_path>/var/log/osquery/osqueryd.results.log</log_path>
          <config_path>/etc/osquery/osquery.conf</config_path>
          <add_labels>yes</add_labels>
        </wodle>

        <wodle name="syscollector">
          <disabled>no</disabled>
          <interval>1h</interval>
          <scan_on_start>yes</scan_on_start>
          <hardware>yes</hardware>
          <os>yes</os>
          <network>yes</network>
          <packages>yes</packages>
          <ports all="no">yes</ports>
          <processes>yes</processes>
        </wodle>

        <syscheck>
          <disabled>no</disabled>
          <frequency>43200</frequency>
          <scan_on_start>yes</scan_on_start>
          <auto_ignore>no</auto_ignore>
          <alert_new_files>yes</alert_new_files>
          <scan_time>8:00</scan_time>
          <scan_day>sunday</scan_day>
          <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
          <directories check_all="yes">/bin,/sbin</directories>
          <ignore>/etc/mtab</ignore>
          <ignore>/etc/hosts.deny</ignore>
          <ignore>/etc/mail/statistics</ignore>
          <ignore>/etc/random-seed</ignore>
          <ignore>/etc/random.seed</ignore>
          <ignore>/etc/adjtime</ignore>
          <ignore>/etc/httpd/logs</ignore>
          <ignore>/etc/utmpx</ignore>
          <ignore>/etc/wtmpx</ignore>
          <ignore>/etc/cups/certs</ignore>
          <ignore>/etc/dumpdates</ignore>
          <ignore>/etc/svc/volatile</ignore>
          <skip_nfs>yes</skip_nfs>
        </syscheck>

        <vulnerability-detector>
          <enabled>yes</enabled>
          <interval>5m</interval>
          <ignore_time>6h</ignore_time>
          <run_on_start>yes</run_on_start>
          <provider name="canonical">
            <enabled>yes</enabled>
            <os>trusty</os>
            <os>xenial</os>
            <os>bionic</os>
            <os>focal</os>
            <update_interval>1h</update_interval>
          </provider>
          <provider name="debian">
            <enabled>yes</enabled>
            <os>stretch</os>
            <os>buster</os>
            <os>bullseye</os>
            <update_interval>1h</update_interval>
          </provider>
          <provider name="redhat">
            <enabled>yes</enabled>
            <update_from_year>2010</update_from_year>
            <update_interval>1h</update_interval>
          </provider>
          <provider name="nvd">
            <enabled>yes</enabled>
            <update_from_year>2010</update_from_year>
            <update_interval>1h</update_interval>
          </provider>
        </vulnerability-detector>

        <command>
          <name>disable-account</name>
          <executable>disable-account.sh</executable>
          <expect>user</expect>
          <timeout_allowed>yes</timeout_allowed>
        </command>

        <active-response>
          <disabled>yes</disabled>
          <command>disable-account</command>
          <location>local</location>
          <rules_id>100100,100101</rules_id>
          <timeout>300</timeout>
        </active-response>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/ossec/logs/active-responses.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/messages</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/auth.log</location>
        </localfile>

        <localfile>
          <log_format>syslog</log_format>
          <location>/var/log/syslog</location>
        </localfile>

        <localfile>
          <log_format>command</log_format>
          <command>df -P</command>
          <frequency>360</frequency>
        </localfile>

        <localfile>
          <log_format>full_command</log_format>
          <command>netstat -tulpn | grep -v 127.0.0.1 | sort</command>
          <frequency>360</frequency>
        </localfile>

        <localfile>
          <log_format>full_command</log_format>
          <command>last -n 20</command>
          <frequency>360</frequency>
        </localfile>

        <ruleset>
          <decoder_dir>etc/decoders</decoder_dir>
          <rule_dir>etc/rules</rule_dir>
          <rule_exclude>0215-policy_rules.xml</rule_exclude>
          <list>etc/lists/audit-keys</list>
          <list>etc/lists/amazon/aws-eventnames</list>
          <list>etc/lists/security-eventchannel</list>
        </ruleset>

        <cluster>
          <name>wazuh</name>
          <node_name>node01</node_name>
          <node_type>master</node_type>
          <key>9d273b53510fef702b54a92e9cffc82e</key>
          <port>1516</port>
          <bind_addr>0.0.0.0</bind_addr>
          <nodes>
            <node>wazuh-manager</node>
          </nodes>
          <hidden>no</hidden>
          <disabled>no</disabled>
        </cluster>
      </ossec_config>

# Certificates configuration
certificates:
  enabled: true
  elasticsearchAdmin:
    name: admin
    password: admin
  indexerUsername: admin
  indexerPassword: admin
  dashboardUsername: admin
  dashboardPassword: admin

# Service account configuration
serviceAccount:
  create: true
  name: wazuh-operator